Время разбивать камни
htmlacademy-ecmascript/1995679-big-trip-simple-19 pull request #3
Opened 2022-12-08 12:27 UTC by AlexeyDemyan

Вопросы:

Взять например main.js:
const pageBodyPageMainElement = pageBodyElement.querySelector('.page-body__page-main');
Как вообще лучше именовать элементы и организовывать querySelector-ы, когда вёрстка сделана по БЭМу?
Как видишь, я ищу так: элемент -> потом внутри него -> еще "внутрее". Я так всегда делал, чтобы подстраховаться, но ты скажи как лучше.

В задании сказано что презентер должен рендерить ВСЁ, но я бы кнопки рендерил сразу в main.js в обход презентера - вот как я и сделал. Скажи как лучше, если что. Опять же эту логику можно поменять, смотря как дальше приложение будем пилить

---
:mortar_board: [Время разбивать камни](https://up.htmlacademy.ru/ecmascript/19/user/1995679/tasks/5)

2022-12-09 08:51 UTC, andreevsm requested changes

2022-12-09 08:51 UTC, andreevsm commented on Readme.md
> +* Наставник: [Сергей Андреев](https://htmlacademy.ru/profile/id812127).
Хмм, эти изменения уже ведь есть в проекте
Видимо, забыл смержить мастер в свою ветку)

2022-12-09 08:51 UTC, andreevsm commented on src/main.js
> +const pageBodyPageMainElement = pageBodyElement.querySelector('.page-body__page-main');
1. По поводу именования
БЭМ используется, чтоб обозначить иерархию элементов (не только для этого, конечно)
А в нашем случае у тебя идут просто переменные, без какого-либо контекста. По крайней мере это самые главные элементы на странице, так что можно просто `bodyElement, mainElement, tripEventsElement, ...`

2. По поводу поиска
Ничего страшного, можно и так искать)

2022-12-09 08:51 UTC, andreevsm commented on src/main.js
> +const tripListPresenter = new TripListPresenter({tripListContainer:tripEventsElement});
А почему через объект? Можно же просто `new TripListPresenter(tripEventsElement)`

2022-12-09 08:51 UTC, andreevsm commented on src/main.js
> +const AMOUNT_OF_DESTINATIONS_TO_RENDER = 3;
Можно попроще, например `DESTINATIONS_COUNT`

2022-12-09 08:51 UTC, andreevsm commented on src/view/destination-item-view.js
> +function createDestinationItemTemplate () {
Думаю, `item` можно убрать)

2022-12-09 08:51 UTC, andreevsm commented on src/view/list-filter-view.js
> +export default class ListFilterView {
А тут можно просто `FilterView` назвать, так как это один полноценный компонент

2022-12-10 11:58 UTC, AlexeyDemyan commented on Readme.md
> +* Наставник: [Сергей Андреев](https://htmlacademy.ru/profile/id812127).
Да, я там что-то натанцевались с Гитом) Ну сейчас, когда начнем всё по порядку делать, будет попроще)

2022-12-10 11:58 UTC, AlexeyDemyan commented on src/main.js
> +const pageBodyPageMainElement = pageBodyElement.querySelector('.page-body__page-main');
Исправил

2022-12-10 12:00 UTC, AlexeyDemyan commented on src/main.js
> +const tripListPresenter = new TripListPresenter({tripListContainer:tripEventsElement});
Сейчас смотрю, а в trip-list-presenter.js у меня в конструкторе передавался объект constructor({tripListContainer}) {}
Это я бездумно с презентации скопирнул, сейчас исправил)

2022-12-10 12:00 UTC, AlexeyDemyan commented on src/main.js
> +const AMOUNT_OF_DESTINATIONS_TO_RENDER = 3;
Перемудрил, согласен, исправил

2022-12-10 12:02 UTC, AlexeyDemyan commented on src/view/destination-item-view.js
> +function createDestinationItemTemplate () {
Да, исправил

2022-12-10 12:05 UTC, AlexeyDemyan commented on src/view/list-filter-view.js
> +export default class ListFilterView {
Исправил. Я просто еще не до конца сообразил, насколько большое будет приложение - думал, может еще какие-то фильтры будут добавляться. Пробежался по markup-ам, плюс-минус понял масштаб функционала.

2022-12-10 18:33 UTC, merged